theme: jekyll-theme-cayman

title: Waddington Optimal Transport
description: Optimal-transport based software tools for single-cell RNA sequencing analysis

repository: broadinstitute/wot

show_downloads: false

navbar_items:
  - title: Home
    url: /
  - title: Documentation
    url: /cli_documentation
  - title: Examples
    url: /examples
  - title: Citing
    url: /citing_wot
  - title: Source Code
    url: /github
